export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USERS = "GET_USERS";
export const GET_CURRENT_LEVEL = "GET_CURRENT_LEVEL";
export const UPDATE_LEVEL = "UPDATE_LEVEL"